name: 'Regenerate Embeddings'
description: 'Regenerate OpenAI word embeddings on every push and store them in Supabase'
author: 'K02D'
inputs:
  github-personal-access-token:
    description: 'Github personal access token'
    required: true
  openai-api-key:
    description: 'OpenAI API key'
    required: true
  supabase-anon-key:
    description: 'Supabase anon key'
    required: true
  supabase-database-password:
    description: 'Supabase database password'
    required: true
  supabase-url:
    description: 'Supabase url'
    required: true
  repository-owner-username:
    description: 'GitHub username of the repository owner'
    required: true
  repository-name:
    description: 'Name of the repository'
    required: true
  path-to-contents:
    description: 'Path to the directory containing subdirectories of files (e.g. notes)'
    required: true
  file-format:
    description: 'File format of the notes'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
